--- # Environment init

- name: Ensure https support for apt is installed
  apt:
    name: apt-transport-https
    state: present

- name: Add repository for PHP 7.0
  apt_repository:
    repo: "ppa:ondrej/php"

- name: Update Apt
  apt: update_cache=yes

- name: Installing unzip (required by composer)
  apt:
    name: unzip
    state: present

- name: Installing required packages
  package: name={{ item }} state=installed
  with_items:
    - vim
    - tmux
    - php7.0-zip
    - php7.0-intl
    - php7.0-pgsql
    - nginx-extras
    - mysql-client
    - drush

- name: Installing php-xdebug if needed
  package: name={{ item }} state=installed
  with_items:
    - php-xdebug
  when: php_xdebug_enabled

#- name: Create drupal.log file dir
#  file:
#    path: /var/log/drupal
#    state: directory
#    mode: 0777

- name: Create drupal.log file
  file:
    path: /var/log/drupal/drupal.log
    state: touch
    mode: 0666