---
# Global vars
# https://docs.ansible.com/ansible/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable

# Nginx
nginx_remove_default_vhost: true

# PHP-FPM
php_enable_php_fpm: true
php_webserver_daemon: nginx
php_opcache_conf_filename: "10-opcache.ini"

# Disabling MySQL server (we need only client on this machine)
mysql_enabled_on_startup: false

# PHP
php_memory_limit: 1G