--- # Final fixes

- name: Set default php-cli to 7.0
  file:
    src: /usr/bin/php7.0
    dest: /usr/bin/php
    state: link

- name: Set up xDebug remote_enable on Docker for Mac
  lineinfile:
    path: /etc/php/7.0/mods-available/xdebug.ini
    regexp: '^xdebug.remote_enable='
    line: 'xdebug.remote_enable=on'
  when: php_xdebug_enabled

- name: Set up xDebug remote_hostname on Docker for Mac
  lineinfile:
    path: /etc/php/7.0/mods-available/xdebug.ini
    regexp: '^xdebug.remote_hostname='
    line: 'xdebug.remote_hostname=docker.for.mac.localhost'
  when: php_xdebug_enabled