--- # Final fixes

- name: Set default php-cli to 7.0
  file:
    src: "{{ item.src }}"
    dest: "{{ item.symlink }}"
    state: link
    force: yes
  with_items:
    - src: /usr/bin/php7.0
      symlink: /etc/alternatives/php
#    - src: /usr/lib/libphp7.so
#      symlink: /etc/alternatives/libphp7
#    - src: /usr/bin/php-config7.0
#      symlink: /etc/alternatives/php

- name: Configure php-fpm pool
  lineinfile:
    dest: "/etc/php/7.0/fpm/pool.d/www.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: "^.?request_terminate_timeout.?=.+$"
      line: "request_terminate_timeout={{ php_fpm_request_terminate_timeout }}"

- name: Set up xDebug on Docker for Mac
  lineinfile:
    path: /etc/php/7.0/mods-available/xdebug.ini
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - regexp: '^xdebug.remote_enable='
      line: 'xdebug.remote_enable=on'
    - regexp: '^xdebug.remote_host='
      line: 'xdebug.remote_host=docker.for.mac.localhost'
  when: php_xdebug_enabled