--- # App

#- name: copy checkbook nginx config
#  copy:
#    src: "settings.php"
#    dest: "{{ project_index_path }}/sites/default/settings.php"

- name: php7.0-fpm status
  command: /etc/init.d/php7.0-fpm status
  register: php_fpm_status
  ignore_errors: true

- name: Start php7.0-fpm
  command: /etc/init.d/php7.0-fpm start
  when: '"is not running" in php_fpm_status.stdout'
  notify: restart nginx

- name: ReStart php7.0-fpm
  command: /etc/init.d/php7.0-fpm restart
  when: '"is running" in php_fpm_status.stdout'
  notify: restart nginx

- name: Fixing /var/www/ permissions
  file:
    path: "/var/www"
    state: directory
    mode: 0755
    recurse: yes